services:
  rag:
    build: ./assistant-rag
    ports:
      - "5000:5000"
    environment:
      - QDRANT_HOST=qdrant
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=mistral
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - RERANKER_MODEL=cross-encoder/ms-marco-MiniLM-L-6-v2
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: assistant
      POSTGRES_USER: assistant
      POSTGRES_PASSWORD: assistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  qdrant_storage:
  pgdata:
