server:
  port: 8888

spring:
  application:
    name: assistant-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thuggeelya/assistant-config-repo.git
          search-paths: "{application}"
          username: thuggeelya
          password: ${CONFIG_SERVER_GIT_TOKEN}
          default-label: master