server:
  port: 8888

spring:
  application:
    name: assistant-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thuggeelya/assistant
          search-paths: config-repo